-- 0030 — Catálogo de commodities do mercado, ligado aos grupos
--
-- A 0029 trouxe os GRUPOS prontos, mas nenhuma commodity dentro deles: escolher
-- "Minérios" abria uma lista vazia. O usuário pediu o contrário — escolher o grupo
-- e ver as commodities DELE para escolher, inserindo nova só quando faltar.
--
--   1. commodities_padrao: 67 commodities do mercado, cada uma no seu grupo, com
--      unidade e referência de preço. É LISTA, não cadastro: igual para todas as
--      empresas, só leitura, e o nome sai do dicionário (4 idiomas) pelo `codigo`.
--   2. A empresa ADOTA a commodity (um clique): nasce uma linha em `commodities`
--      com `padrao_codigo` — é nela que ficam grades, especificação e contratos.
--      Adotar duas vezes é recusado pelo índice único.
--   3. As commodities que as empresas já têm são encaixadas no grupo e ligadas ao
--      catálogo quando o nome bate (pt, en, es ou apelido comum, com ou sem acento).
--      Nome que não bate fica como está, em "Sem grupo".
--
-- Sem PL/pgSQL. Idempotente (rodar de novo atualiza a lista, não duplica).
-- Gerado de uma fonte só com os dicionários. Teste: tests/schema20.test.sql.

-- ---------------------------------------------------------------------------
-- BLOCO 1 — a lista do mercado
-- ---------------------------------------------------------------------------
create table if not exists public.commodities_padrao (
  codigo        text primary key check (codigo ~ '^[a-z0-9_]{2,40}$'),
  grupo_codigo  text not null check (grupo_codigo in ('carvao', 'fertilizantes', 'florestais', 'gas_natural', 'graos_oleaginosas', 'metais_basicos', 'metais_preciosos', 'minerios', 'petroleo_derivados', 'proteinas', 'quimicos', 'softs')),
  unidade       text not null check (char_length(unidade) between 1 and 40),
  referencia    text check (referencia is null or char_length(referencia) <= 160),
  ordem         int not null default 0
);

alter table public.commodities_padrao enable row level security;

drop policy if exists commodities_padrao_ver on public.commodities_padrao;

create policy commodities_padrao_ver on public.commodities_padrao for select to authenticated using (true);

grant select on public.commodities_padrao to authenticated;

insert into public.commodities_padrao (codigo, grupo_codigo, unidade, referencia, ordem) values
  ('iron_ore', 'minerios', 'Toneladas', 'Platts IODEX 62% Fe CFR China', 0),
  ('iron_ore_pellets', 'minerios', 'Toneladas', 'Platts IO Pellet Premium', 10),
  ('manganese_ore', 'minerios', 'Toneladas', 'Fastmarkets Mn 37% CIF Tianjin', 20),
  ('chrome_ore', 'minerios', 'Toneladas', 'Fastmarkets Chrome Ore 42% CIF China', 30),
  ('copper_concentrate', 'minerios', 'Toneladas', 'LME Copper (payable)', 40),
  ('zinc_concentrate', 'minerios', 'Toneladas', 'LME Zinc (payable)', 50),
  ('lead_concentrate', 'minerios', 'Toneladas', 'LME Lead (payable)', 60),
  ('bauxite', 'minerios', 'Toneladas', 'CM Bauxite CIF China', 70),
  ('spodumene', 'minerios', 'Toneladas', 'Fastmarkets Spodumene SC6 CIF China', 80),
  ('copper_cathode', 'metais_basicos', 'Toneladas', 'LME Copper Grade A', 90),
  ('aluminium', 'metais_basicos', 'Toneladas', 'LME Aluminium', 100),
  ('zinc', 'metais_basicos', 'Toneladas', 'LME Zinc SHG', 110),
  ('nickel', 'metais_basicos', 'Toneladas', 'LME Nickel', 120),
  ('lead', 'metais_basicos', 'Toneladas', 'LME Lead', 130),
  ('tin', 'metais_basicos', 'Toneladas', 'LME Tin', 140),
  ('pig_iron', 'metais_basicos', 'Toneladas', 'Argus Pig Iron FOB Brazil', 150),
  ('steel_billet', 'metais_basicos', 'Toneladas', 'Platts Billet FOB Black Sea', 160),
  ('gold', 'metais_preciosos', 'Onças troy', 'LBMA Gold Price', 170),
  ('silver', 'metais_preciosos', 'Onças troy', 'LBMA Silver Price', 180),
  ('platinum', 'metais_preciosos', 'Onças troy', 'LPPM Platinum', 190),
  ('palladium', 'metais_preciosos', 'Onças troy', 'LPPM Palladium', 200),
  ('crude_oil', 'petroleo_derivados', 'Barris', 'ICE Brent', 210),
  ('diesel_en590', 'petroleo_derivados', 'Toneladas', 'Platts ULSD 10ppm', 220),
  ('jet_a1', 'petroleo_derivados', 'Toneladas', 'Platts Jet/Kero', 230),
  ('gasoline', 'petroleo_derivados', 'Toneladas', 'Platts Eurobob', 240),
  ('fuel_oil', 'petroleo_derivados', 'Toneladas', 'Platts VLSFO 0.5%', 250),
  ('naphtha', 'petroleo_derivados', 'Toneladas', 'Platts Naphtha CIF NWE', 260),
  ('lpg', 'petroleo_derivados', 'Toneladas', 'Saudi Aramco CP', 270),
  ('lng', 'gas_natural', 'MMBtu', 'Platts JKM', 280),
  ('natural_gas', 'gas_natural', 'MMBtu', 'NYMEX Henry Hub', 290),
  ('thermal_coal', 'carvao', 'Toneladas', 'API2 CIF ARA / Newcastle', 300),
  ('coking_coal', 'carvao', 'Toneladas', 'Platts PLV HCC FOB Australia', 310),
  ('petcoke', 'carvao', 'Toneladas', 'Argus Petcoke', 320),
  ('soybeans', 'graos_oleaginosas', 'Toneladas', 'CBOT Soybeans', 330),
  ('corn', 'graos_oleaginosas', 'Toneladas', 'CBOT Corn', 340),
  ('wheat', 'graos_oleaginosas', 'Toneladas', 'CBOT Wheat', 350),
  ('soybean_meal', 'graos_oleaginosas', 'Toneladas', 'CBOT Soybean Meal', 360),
  ('soybean_oil', 'graos_oleaginosas', 'Toneladas', 'CBOT Soybean Oil', 370),
  ('rice', 'graos_oleaginosas', 'Toneladas', 'CBOT Rough Rice', 380),
  ('sunflower_oil', 'graos_oleaginosas', 'Toneladas', 'Argus Sunflower Oil FOB Black Sea', 390),
  ('sugar_icumsa45', 'softs', 'Toneladas', 'ICE White Sugar No. 5', 400),
  ('sugar_vhp', 'softs', 'Toneladas', 'ICE Raw Sugar No. 11', 410),
  ('coffee_arabica', 'softs', 'Toneladas', 'ICE Coffee "C"', 420),
  ('coffee_robusta', 'softs', 'Toneladas', 'ICE Robusta Coffee', 430),
  ('cocoa', 'softs', 'Toneladas', 'ICE Cocoa', 440),
  ('cotton', 'softs', 'Toneladas', 'ICE Cotton No. 2', 450),
  ('orange_juice', 'softs', 'Toneladas', 'ICE FCOJ', 460),
  ('ethanol', 'softs', 'm³', 'Platts Ethanol T2 FOB Rotterdam', 470),
  ('urea', 'fertilizantes', 'Toneladas', 'Platts Granular Urea FOB Middle East', 480),
  ('dap', 'fertilizantes', 'Toneladas', 'Argus DAP FOB', 490),
  ('map', 'fertilizantes', 'Toneladas', 'Argus MAP CFR Brazil', 500),
  ('potash', 'fertilizantes', 'Toneladas', 'Argus MOP CFR Brazil', 510),
  ('ammonium_nitrate', 'fertilizantes', 'Toneladas', 'Argus AN FOB Baltic', 520),
  ('ammonia', 'fertilizantes', 'Toneladas', 'Argus Ammonia CFR Tampa', 530),
  ('sulphur', 'fertilizantes', 'Toneladas', 'Argus Sulphur FOB Middle East', 540),
  ('methanol', 'quimicos', 'Toneladas', 'Methanex Posted Contract Price', 550),
  ('caustic_soda', 'quimicos', 'Toneladas', 'Argus Caustic Soda', 560),
  ('sulphuric_acid', 'quimicos', 'Toneladas', 'Argus Sulphuric Acid', 570),
  ('polyethylene', 'quimicos', 'Toneladas', 'Platts PE', 580),
  ('polypropylene', 'quimicos', 'Toneladas', 'Platts PP', 590),
  ('beef', 'proteinas', 'Toneladas', 'CEPEA Boi Gordo', 600),
  ('chicken', 'proteinas', 'Toneladas', 'CEPEA Frango', 610),
  ('pork', 'proteinas', 'Toneladas', 'CME Lean Hogs', 620),
  ('pulp_bekp', 'florestais', 'Toneladas', 'FOEX PIX BHKP China', 630),
  ('pulp_nbsk', 'florestais', 'Toneladas', 'FOEX PIX NBSK', 640),
  ('timber', 'florestais', 'm³', '—', 650),
  ('wood_pellets', 'florestais', 'Toneladas', 'Argus Wood Pellets CIF ARA', 660)
on conflict (codigo) do update
  set grupo_codigo = excluded.grupo_codigo, unidade = excluded.unidade,
      referencia = excluded.referencia, ordem = excluded.ordem;

-- ---------------------------------------------------------------------------
-- BLOCO 2 — a commodity da empresa lembra de qual item do catálogo veio
-- ---------------------------------------------------------------------------
alter table public.commodities add column if not exists padrao_codigo text
  references public.commodities_padrao (codigo) on delete set null;

create unique index if not exists commodities_padrao_uq
  on public.commodities (organizacao_id, padrao_codigo) where padrao_codigo is not null;

-- ---------------------------------------------------------------------------
-- BLOCO 3 — encaixa no grupo o que as empresas já tinham (uma por item e empresa)
-- ---------------------------------------------------------------------------
update public.commodities c
   set grupo_id = s.grupo_id, padrao_codigo = s.codigo
  from (
    select distinct on (x.organizacao_id, p.codigo) x.id, p.codigo, g.id as grupo_id
      from public.commodities x
      join (values
        ('iron_ore', 'iron ore'),
        ('iron_ore', 'iron ore fines'),
        ('iron_ore', 'mineral de hierro'),
        ('iron_ore', 'minerio de ferro'),
        ('iron_ore', 'minério de ferro'),
        ('iron_ore_pellets', 'iron ore pellets'),
        ('iron_ore_pellets', 'pellets'),
        ('iron_ore_pellets', 'pellets de mineral de hierro'),
        ('iron_ore_pellets', 'pelotas'),
        ('iron_ore_pellets', 'pelotas de minerio de ferro'),
        ('iron_ore_pellets', 'pelotas de minério de ferro'),
        ('manganese_ore', 'manganes'),
        ('manganese_ore', 'manganese ore'),
        ('manganese_ore', 'manganês'),
        ('manganese_ore', 'mineral de manganeso'),
        ('manganese_ore', 'minerio de manganes'),
        ('manganese_ore', 'minério de manganês'),
        ('chrome_ore', 'chrome ore'),
        ('chrome_ore', 'cromita'),
        ('chrome_ore', 'cromo'),
        ('chrome_ore', 'mineral de cromo'),
        ('chrome_ore', 'minerio de cromo'),
        ('chrome_ore', 'minério de cromo'),
        ('copper_concentrate', 'concentrado de cobre'),
        ('copper_concentrate', 'copper concentrate'),
        ('zinc_concentrate', 'concentrado de zinc'),
        ('zinc_concentrate', 'concentrado de zinco'),
        ('zinc_concentrate', 'zinc concentrate'),
        ('lead_concentrate', 'concentrado de chumbo'),
        ('lead_concentrate', 'concentrado de plomo'),
        ('lead_concentrate', 'lead concentrate'),
        ('bauxite', 'bauxita'),
        ('bauxite', 'bauxite'),
        ('spodumene', 'espodumenio'),
        ('spodumene', 'espodumenio (litio)'),
        ('spodumene', 'espodumeno (litio)'),
        ('spodumene', 'espodumênio (lítio)'),
        ('spodumene', 'litio'),
        ('spodumene', 'lítio'),
        ('spodumene', 'spodumene (lithium)'),
        ('copper_cathode', 'catodo de cobre'),
        ('copper_cathode', 'cobre'),
        ('copper_cathode', 'cobre catodo'),
        ('copper_cathode', 'copper cathode'),
        ('copper_cathode', 'cátodo de cobre'),
        ('aluminium', 'aluminio'),
        ('aluminium', 'aluminio primario'),
        ('aluminium', 'alumínio'),
        ('aluminium', 'alumínio primário'),
        ('aluminium', 'primary aluminium'),
        ('zinc', 'zinc'),
        ('zinc', 'zinco'),
        ('nickel', 'nickel'),
        ('nickel', 'niquel'),
        ('nickel', 'níquel'),
        ('lead', 'chumbo'),
        ('lead', 'lead'),
        ('lead', 'plomo'),
        ('tin', 'estanho'),
        ('tin', 'estano'),
        ('tin', 'estaño'),
        ('tin', 'tin'),
        ('pig_iron', 'arrabio'),
        ('pig_iron', 'ferro gusa'),
        ('pig_iron', 'ferro-gusa'),
        ('pig_iron', 'gusa'),
        ('pig_iron', 'pig iron'),
        ('steel_billet', 'palanquilla de acero'),
        ('steel_billet', 'steel billet'),
        ('steel_billet', 'tarugo'),
        ('steel_billet', 'tarugo de aco'),
        ('steel_billet', 'tarugo de aço'),
        ('gold', 'gold'),
        ('gold', 'oro'),
        ('gold', 'ouro'),
        ('silver', 'plata'),
        ('silver', 'prata'),
        ('silver', 'silver'),
        ('platinum', 'platina'),
        ('platinum', 'platino'),
        ('platinum', 'platinum'),
        ('palladium', 'paladio'),
        ('palladium', 'palladium'),
        ('palladium', 'paládio'),
        ('crude_oil', 'crude'),
        ('crude_oil', 'crude oil'),
        ('crude_oil', 'petroleo'),
        ('crude_oil', 'petroleo bruto'),
        ('crude_oil', 'petroleo crudo'),
        ('crude_oil', 'petróleo'),
        ('crude_oil', 'petróleo bruto'),
        ('crude_oil', 'petróleo crudo'),
        ('diesel_en590', 'diesel'),
        ('diesel_en590', 'diesel en590'),
        ('diesel_en590', 'diésel en590'),
        ('diesel_en590', 'ulsd'),
        ('jet_a1', 'combustible de aviacion (jet a-1)'),
        ('jet_a1', 'combustible de aviación (jet a-1)'),
        ('jet_a1', 'jet a-1'),
        ('jet_a1', 'jet a1'),
        ('jet_a1', 'jet fuel (jet a-1)'),
        ('jet_a1', 'querosene'),
        ('jet_a1', 'querosene de aviacao (jet a-1)'),
        ('jet_a1', 'querosene de aviação (jet a-1)'),
        ('gasoline', 'gasolina'),
        ('gasoline', 'gasoline'),
        ('fuel_oil', 'fuel oil (vlsfo/hsfo)'),
        ('fuel_oil', 'fueloleo (vlsfo/hsfo)'),
        ('fuel_oil', 'fuelóleo (vlsfo/hsfo)'),
        ('fuel_oil', 'hsfo'),
        ('fuel_oil', 'oleo combustivel'),
        ('fuel_oil', 'oleo combustivel (vlsfo/hsfo)'),
        ('fuel_oil', 'vlsfo'),
        ('fuel_oil', 'óleo combustível'),
        ('fuel_oil', 'óleo combustível (vlsfo/hsfo)'),
        ('naphtha', 'nafta'),
        ('naphtha', 'naphtha'),
        ('lpg', 'glp'),
        ('lpg', 'lpg'),
        ('lng', 'gas natural licuado (gnl)'),
        ('lng', 'gas natural liquefeito (gnl)'),
        ('lng', 'gnl'),
        ('lng', 'gás natural liquefeito (gnl)'),
        ('lng', 'liquefied natural gas (lng)'),
        ('lng', 'lng'),
        ('natural_gas', 'gas natural'),
        ('natural_gas', 'gás natural'),
        ('natural_gas', 'natural gas'),
        ('thermal_coal', 'carbon termico'),
        ('thermal_coal', 'carbón térmico'),
        ('thermal_coal', 'carvao'),
        ('thermal_coal', 'carvao termico'),
        ('thermal_coal', 'carvão'),
        ('thermal_coal', 'carvão térmico'),
        ('thermal_coal', 'steam coal'),
        ('thermal_coal', 'thermal coal'),
        ('coking_coal', 'carbon metalurgico'),
        ('coking_coal', 'carbón metalúrgico'),
        ('coking_coal', 'carvao metalurgico'),
        ('coking_coal', 'carvão metalúrgico'),
        ('coking_coal', 'coking coal'),
        ('coking_coal', 'met coal'),
        ('petcoke', 'coque'),
        ('petcoke', 'coque de petroleo'),
        ('petcoke', 'coque de petróleo'),
        ('petcoke', 'pet coke'),
        ('petcoke', 'petroleum coke'),
        ('soybeans', 'soja'),
        ('soybeans', 'soja em grao'),
        ('soybeans', 'soja em grão'),
        ('soybeans', 'soja en grano'),
        ('soybeans', 'soybean'),
        ('soybeans', 'soybeans'),
        ('corn', 'corn'),
        ('corn', 'maiz'),
        ('corn', 'maize'),
        ('corn', 'maíz'),
        ('corn', 'milho'),
        ('wheat', 'trigo'),
        ('wheat', 'wheat'),
        ('soybean_meal', 'farelo'),
        ('soybean_meal', 'farelo de soja'),
        ('soybean_meal', 'harina de soja'),
        ('soybean_meal', 'soybean meal'),
        ('soybean_oil', 'aceite de soja'),
        ('soybean_oil', 'oleo de soja'),
        ('soybean_oil', 'soybean oil'),
        ('soybean_oil', 'óleo de soja'),
        ('rice', 'arroz'),
        ('rice', 'rice'),
        ('sunflower_oil', 'aceite de girasol'),
        ('sunflower_oil', 'oleo de girassol'),
        ('sunflower_oil', 'sunflower oil'),
        ('sunflower_oil', 'óleo de girassol'),
        ('sugar_icumsa45', 'acucar'),
        ('sugar_icumsa45', 'acucar refinado icumsa 45'),
        ('sugar_icumsa45', 'azucar refinado icumsa 45'),
        ('sugar_icumsa45', 'azúcar refinado icumsa 45'),
        ('sugar_icumsa45', 'açúcar'),
        ('sugar_icumsa45', 'açúcar refinado icumsa 45'),
        ('sugar_icumsa45', 'icumsa 45'),
        ('sugar_icumsa45', 'refined sugar icumsa 45'),
        ('sugar_vhp', 'acucar bruto vhp'),
        ('sugar_vhp', 'acucar vhp'),
        ('sugar_vhp', 'azucar crudo vhp'),
        ('sugar_vhp', 'azúcar crudo vhp'),
        ('sugar_vhp', 'açúcar bruto vhp'),
        ('sugar_vhp', 'raw sugar vhp'),
        ('sugar_vhp', 'vhp'),
        ('coffee_arabica', 'arabica coffee'),
        ('coffee_arabica', 'cafe'),
        ('coffee_arabica', 'cafe arabica'),
        ('coffee_arabica', 'café'),
        ('coffee_arabica', 'café arábica'),
        ('coffee_robusta', 'cafe robusta'),
        ('coffee_robusta', 'cafe robusta (conilon)'),
        ('coffee_robusta', 'café robusta'),
        ('coffee_robusta', 'café robusta (conilon)'),
        ('coffee_robusta', 'conilon'),
        ('coffee_robusta', 'robusta coffee'),
        ('cocoa', 'cacao'),
        ('cocoa', 'cacau'),
        ('cocoa', 'cocoa'),
        ('cotton', 'algodao'),
        ('cotton', 'algodon'),
        ('cotton', 'algodão'),
        ('cotton', 'algodón'),
        ('cotton', 'cotton'),
        ('orange_juice', 'jugo de naranja (fcoj)'),
        ('orange_juice', 'orange juice (fcoj)'),
        ('orange_juice', 'suco de laranja'),
        ('orange_juice', 'suco de laranja (fcoj)'),
        ('ethanol', 'etanol'),
        ('ethanol', 'ethanol'),
        ('urea', 'urea'),
        ('urea', 'ureia'),
        ('urea', 'ureia granulada'),
        ('dap', 'dap (diammonium phosphate)'),
        ('dap', 'dap (fosfato diamonico)'),
        ('dap', 'dap (fosfato diamónico)'),
        ('dap', 'dap (fosfato diamônico)'),
        ('map', 'map (fosfato monoamonico)'),
        ('map', 'map (fosfato monoamónico)'),
        ('map', 'map (fosfato monoamônico)'),
        ('map', 'map (monoammonium phosphate)'),
        ('potash', 'cloreto de potassio (kcl)'),
        ('potash', 'cloreto de potássio (kcl)'),
        ('potash', 'cloruro de potasio (mop)'),
        ('potash', 'kcl'),
        ('potash', 'potash (mop)'),
        ('potash', 'potassio'),
        ('potash', 'potássio'),
        ('ammonium_nitrate', 'ammonium nitrate'),
        ('ammonium_nitrate', 'nitrato de amonio'),
        ('ammonium_nitrate', 'nitrato de amônio'),
        ('ammonia', 'ammonia'),
        ('ammonia', 'amonia'),
        ('ammonia', 'amoniaco'),
        ('ammonia', 'amoníaco'),
        ('ammonia', 'amônia'),
        ('sulphur', 'azufre'),
        ('sulphur', 'enxofre'),
        ('sulphur', 'sulphur'),
        ('methanol', 'metanol'),
        ('methanol', 'methanol'),
        ('caustic_soda', 'caustic soda'),
        ('caustic_soda', 'soda caustica'),
        ('caustic_soda', 'soda cáustica'),
        ('sulphuric_acid', 'acido sulfurico'),
        ('sulphuric_acid', 'sulphuric acid'),
        ('sulphuric_acid', 'ácido sulfúrico'),
        ('polyethylene', 'polietileno'),
        ('polyethylene', 'polyethylene'),
        ('polypropylene', 'polipropileno'),
        ('polypropylene', 'polypropylene'),
        ('beef', 'beef'),
        ('beef', 'carne bovina'),
        ('chicken', 'carne de frango'),
        ('chicken', 'carne de pollo'),
        ('chicken', 'chicken'),
        ('chicken', 'frango'),
        ('pork', 'carne de cerdo'),
        ('pork', 'carne suina'),
        ('pork', 'carne suína'),
        ('pork', 'pork'),
        ('pork', 'suino'),
        ('pulp_bekp', 'celulosa de eucalipto (bekp)'),
        ('pulp_bekp', 'celulose'),
        ('pulp_bekp', 'celulose de eucalipto (bekp)'),
        ('pulp_bekp', 'eucalyptus pulp (bekp)'),
        ('pulp_nbsk', 'celulosa de fibra larga (nbsk)'),
        ('pulp_nbsk', 'celulose de fibra longa (nbsk)'),
        ('pulp_nbsk', 'softwood pulp (nbsk)'),
        ('timber', 'madeira'),
        ('timber', 'madeira serrada'),
        ('timber', 'madera aserrada'),
        ('timber', 'sawn timber'),
        ('wood_pellets', 'pellets de madeira'),
        ('wood_pellets', 'pellets de madera'),
        ('wood_pellets', 'wood pellets')
      ) as a (codigo, apelido) on a.apelido = lower(trim(x.nome))
      join public.commodities_padrao p on p.codigo = a.codigo
      join public.commodity_grupos g on g.codigo = p.grupo_codigo and g.organizacao_id is null
     where x.padrao_codigo is null
       and not exists (select 1 from public.commodities y
                        where y.organizacao_id = x.organizacao_id and y.padrao_codigo = p.codigo)
     order by x.organizacao_id, p.codigo, x.criado_em, x.id
  ) s
 where c.id = s.id;

-- ---------------------------------------------------------------------------
-- BLOCO 4 — conferência: tem que voltar true nas duas colunas.
-- ---------------------------------------------------------------------------
select (select count(*) from public.commodities_padrao) = 67 as catalogo_mercado,
       exists (select 1 from information_schema.columns
                where table_name = 'commodities' and column_name = 'padrao_codigo') as vinculo_catalogo;
